/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-12-05 09:32:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jsh.util.Tools;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jsh.util.Tools");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
    String clientIp = Tools.getLocalIp(request);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>ERP系统</title>\r\n");
      out.write("    <link href=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/HoorayLibs/hooraylibs.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/img/ui/index.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"loading\"></div>\r\n");
      out.write("<!-- 浏览器升级提示 -->\r\n");
      out.write("<div class=\"update_browser_box\">\r\n");
      out.write("    <div class=\"update_browser\">\r\n");
      out.write("        <div class=\"subtitle\">您正在使用的IE浏览器版本过低，<br>我们建议您升级或者更换浏览器，以便体验顺畅、兼容、安全的互联网。</div>\r\n");
      out.write("        <div class=\"title\">选择一款<span>新</span>浏览器吧</div>\r\n");
      out.write("        <div class=\"browser\">\r\n");
      out.write("            <a href=\"http://windows.microsoft.com/zh-CN/internet-explorer/downloads/ie\" class=\"ie\" target=\"_blank\"\r\n");
      out.write("               title=\"ie浏览器\">ie浏览器</a>\r\n");
      out.write("            <a href=\"http://www.google.cn/chrome/\" class=\"chrome\" target=\"_blank\" title=\"谷歌浏览器\">谷歌浏览器</a>\r\n");
      out.write("            <a href=\"http://www.firefox.com.cn\" class=\"firefox\" target=\"_blank\" title=\"火狐浏览器\">火狐浏览器</a>\r\n");
      out.write("            <a href=\"http://www.opera.com\" class=\"opera\" target=\"_blank\" title=\"opera浏览器\">opera浏览器</a>\r\n");
      out.write("            <a href=\"http://www.apple.com.cn/safari\" class=\"safari\" target=\"_blank\" title=\"safari浏览器\">safari浏览器</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bottomtitle\">[&nbsp;<a href=\"http://www.baidu.com/search/theie6countdown.html\" target=\"_blank\">对IE6说再见</a>&nbsp;]\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 桌面 -->\r\n");
      out.write("<div id=\"desktop\">\r\n");
      out.write("    <div id=\"zoom-tip\">\r\n");
      out.write("        <div><i>​</i>​<span></span></div>\r\n");
      out.write("        <a href=\"javascript:;\" class=\"close\" onclick=\"HROS.zoom.close();\">×</a></div>\r\n");
      out.write("    <div id=\"desk\">\r\n");
      out.write("        <div id=\"desk-1\" class=\"desktop-container\">\r\n");
      out.write("            <div class=\"scrollbar scrollbar-x\"></div>\r\n");
      out.write("            <div class=\"scrollbar scrollbar-y\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"dock-bar\">\r\n");
      out.write("            <div id=\"dock-container\">\r\n");
      out.write("                <div class=\"dock-middle\">\r\n");
      out.write("                    <div class=\"dock-applist\"></div>\r\n");
      out.write("                    <div class=\"dock-toollist\">\r\n");
      out.write("                        <a id=\"loginOut\" href=\"#\">\r\n");
      out.write("                            <img src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/img/exit.png\" style=\"height:50px;width:50px;\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <span style=\"text-align:center;color:white; position:absolute;top:435px; left:15px;\">\r\n");
      out.write("                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"task-bar-bg1\"></div>\r\n");
      out.write("    <div id=\"task-bar-bg2\"></div>\r\n");
      out.write("    <div id=\"task-bar\">\r\n");
      out.write("        <div id=\"task-next\"><a href=\"javascript:;\" id=\"task-next-btn\" hidefocus=\"true\"></a></div>\r\n");
      out.write("        <div id=\"task-content\">\r\n");
      out.write("            <div id=\"task-content-inner\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"task-pre\"><a href=\"javascript:;\" id=\"task-pre-btn\" hidefocus=\"true\"></a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/HoorayLibs/hooraylibs.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/templates.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/core.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.app.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.base.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.desktop.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.dock.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.grid.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.maskBox.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.taskbar.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.popupMenu.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.wallpaper.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.widget.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.window.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/js/HoorayOS_mini/js/hros.zoom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/easyui-1.3.5/jquery.easyui.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/js/easyui-1.3.5/themes/default/easyui.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(function () {\r\n");
      out.write("        $('#loginOut').click(function () {\r\n");
      out.write("            if (confirm(\"确认要退出系统吗？\"))\r\n");
      out.write("                location.href = '");
      out.print(path);
      out.write("/user/logout.action?clientIp=");
      out.print(clientIp);
      out.write("';\r\n");
      out.write("        })\r\n");
      out.write("        //IE下禁止选中\r\n");
      out.write("        document.body.onselectstart = document.body.ondrag = function () {\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        //隐藏加载遮罩层\r\n");
      out.write("        $('.loading').hide();\r\n");
      out.write("        //IE6升级提示\r\n");
      out.write("        if ($.browser.msie && $.browser.version < 7) {\r\n");
      out.write("            if ($.browser.version < 7) {\r\n");
      out.write("                //虽然不支持IE6，但还是得修复PNG图片透明的问题\r\n");
      out.write("                DD_belatedPNG.fix('.update_browser .browser');\r\n");
      out.write("            }\r\n");
      out.write("            $('.update_browser_box').show();\r\n");
      out.write("        } else {\r\n");
      out.write("            $('#desktop').show();\r\n");
      out.write("            //初始化一些桌面信息\r\n");
      out.write("            HROS.CONFIG.wallpaper = '");
      out.print(path);
      out.write("/js/HoorayOS_mini/img/wallpaper/wallpaper.jpg';\r\n");
      out.write("            //加载桌面\r\n");
      out.write("            HROS.base.init();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //判断是否存在session，如果不存在就跳到登录界面\r\n");
      out.write("        function UserOut() {\r\n");
      out.write("            var kid = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("            if (!kid) {\r\n");
      out.write("                top.location.href = '../../';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        setInterval(UserOut, 5000); //每5秒检测一次\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
